namespace org.bouncycastle.openpgp.@operator
{
	using ContainedPacket = org.bouncycastle.bcpg.ContainedPacket;
	using SymmetricKeyAlgorithmTags = org.bouncycastle.bcpg.SymmetricKeyAlgorithmTags;

	/// <summary>
	/// An encryption method that can be applied to encrypt data in a <seealso cref="PGPEncryptedDataGenerator"/>.
	/// </summary>
	public abstract class PGPKeyEncryptionMethodGenerator
	{
		/// <summary>
		/// Generates a packet encoding the details of this encryption method.
		/// </summary>
		/// <param name="encAlgorithm"> the <seealso cref="SymmetricKeyAlgorithmTags encryption algorithm"/> being used </param>
		/// <param name="sessionInfo"> session data generated by the encrypted data generator. </param>
		/// <returns> a packet encoding the provided information and the configuration of this instance. </returns>
		/// <exception cref="PGPException"> if an error occurs constructing the packet. </exception>
		public abstract ContainedPacket generate(int encAlgorithm, byte[] sessionInfo);
	}

}